"""Constants for the Eaton xStorage Hybrid integration."""

# Domain name for the integration
DOMAIN = "xStorage-Hybrid-HASS-Integration"

# Configuration keys
CONF_HOST = "host"
CONF_PORT = "port"

# Default values
DEFAULT_PORT = 502  # Standard Modbus TCP port
DEFAULT_SCAN_INTERVAL = 30  # seconds

# Device information
MANUFACTURER = "Eaton"
MODEL = "xStorage Hybrid"

# Modbus register addresses (these should be adjusted based on actual de vice specification)
# Example registers - replace with actual xStorage Hybrid register addresses
REGISTER_STATE_OF_CHARGE = 1000  # Example register address for SoC


REGISTER_LIST: dict[int, dict] = {
    3000: {"name": "PV1 Input Vlot", "unit": "(0.1V)"},
    3001: {"name": "PV2 Input Vlot", "unit": "(0.1V)"},
    3013: {"name": "PV2 Input Curr", "unit": "(0.01A)"},
    3024: {"name": "PV1 Input Power", "unit": "(1W)"},
    3025: {"name": "PV2 Input Power", "unit": "(1W)"},
    3037: {"name": "Month Energy (PV)", "unit": "(Kwh)"},
    3038: {"name": "04H 3039 Year Energy (PV)", "unit": "(Kwh)"},
    3040: {"name": "04H 3041 Total Energy (PV)", "unit": "(0.1Kwh)"},
    3042: {"name": "04H 3043 Reserved 2 86 04H 3044 Inverter working mode", "unit": ""},
    3045: {"name": "Inverter Model", "unit": ""},
    3046: {"name": "SYS_STATE", "unit": ""},
    3047: {"name": "INV_STATE", "unit": ""},
    3048: {"name": "DCDC_STATE", "unit": ""},
    3049: {"name": "DSP alarm code", "unit": ""},
    3050: {"name": "04H 3051 DSP error code", "unit": ""},
    3052: {"name": "04H 3053 BUS Volt", "unit": "(0.1V)"},
    3054: {"name": "DCBUS Vlot", "unit": "(0.1V)"},
    3059: {"name": "Discharge Depth Enable", "unit": ""},
    3060: {"name": "BMS DOD Enable", "unit": ""},
    3062: {"name": "BAT Type 2 124 U16 04H 3063 BAT Volt", "unit": "(0.01V)"},
    3063: {"name": "BAT Volt", "unit": "(0.01V)"},
    3064: {"name": "BAT Current", "unit": "(0.1A)"},
    3065: {"name": "BAT CHG/DISCHG Power", "unit": "(1W)"},
    3066: {"name": "BAT_SOC", "unit": "(0.10%)"},
    3067: {"name": "BAT_Temp", "unit": "(0.1℃)"},
    3068: {"name": "OnGrid DISC -DEPTH", "unit": "(%)"},
    3069: {"name": "BAT_CHG_VOLT", "unit": "(0.1V)"},
    3070: {"name": "BAT_CHG_LIMIT_CURR", "unit": "(1A)"},
    3071: {"name": "BAT_DISCHG_LIMIT_CURR", "unit": "(1A)"},
    3072: {"name": "Min Bat DisChg Volt", "unit": "(0.1V)"},
    3073: {"name": "Max Bat Chg Volt", "unit": "(0.1V)"},
    3074: {"name": "BAT_CAP_AH", "unit": "(Ah)"},
    3075: {"name": "BAT Health 150 0.10% U16 04H 3076 Reserved", "unit": ""},
    3077: {"name": "Number of battery packs", "unit": ""},
    3078: {"name": "BAT Dischg Power Set", "unit": "(%)"},
    3079: {"name": "BAT Charge Power Set", "unit": "(%)"},
    3080: {"name": "BAT_SET_FLOAT_VOLT", "unit": "(0.1V)"},
    3081: {"name": "BAT_SET _AVERA_VOLT", "unit": "(0.1V)"},
    3082: {"name": "BAT_SET_CHG_CURR", "unit": "(1A)"},
    3083: {"name": "Wake -up BMS Enb", "unit": ""},
    3084: {"name": "Wake -up BMS Time", "unit": "(min)"},
    # 3086: {"name": "Force Chg/Dischg Enb", "unit": ""},
    # 3098: {"name": "R Phase Grid Freq", "unit": "(0.01Hz)"},
    # 3099: {"name": "R Phase Meter Curr", "unit": "(0.001A)"},
    # 3100: {"name": "R Phase Meter Power", "unit": "(1W)"},
    # 3101: {"name": "S Phase Grid Volt", "unit": "(0.1V)"},
    # 3102: {"name": "S Phase Grid Freq", "unit": "(0.01Hz)"},
    # 3103: {"name": "S Phase Meter Curr", "unit": "(0.001A)"},
    # 3104: {"name": "S Phase Meter Power", "unit": "(1W)"},
    # 3105: {"name": "T Phase Grid Volt", "unit": "(0.1V)"},
    # 3106: {"name": "T Phase Grid Freq", "unit": "(0.01Hz)"},
    # 3107: {"name": "T Phase Meter Curr", "unit": "(0.001A)"},
    # 3108: {"name": "T Phase Meter Power", "unit": "(1W)"},
    # 3109: {"name": "Day Energy (BUY)", "unit": "(0.1Kwh)"},
    # 3110: {"name": "Month Energy (BUY)", "unit": "(Kwh)"},
    # 3115: {"name": "04H 3116 Day Energy (SELL)", "unit": "(0.1Kwh)"},
    # 3117: {"name": "Month Energy (SE LL)", "unit": "(Kwh)"},
    # 3118: {"name": "04H 3119 Year Energy (SELL)", "unit": "(Kwh)"},
    # 3120: {"name": "04H 3121 Total Energy (SELL)", "unit": "(0.1Kwh)"},
    # 3122: {"name": "04H 3123 R-INV_Vlot", "unit": "(0.1V)"},
    # 3124: {"name": "R-INV_Curr", "unit": "(0.01A)"},
    # 3125: {"name": "R-INV_Freq", "unit": "(0.01Hz)"},
    # 3126: {"name": "R-INV_Power", "unit": "(1W)"},
    # 3127: {"name": "S-INV_Vlot", "unit": "(0.1V)"},
    # 3128: {"name": "S-INV_Curr", "unit": "(0.01A)"},
    # 3129: {"name": "S-INV_Freq", "unit": "(0.01Hz)"},
    # 3130: {"name": "S-INV_Power", "unit": "(1W)"},
    # 3131: {"name": "T-INV_Vlot", "unit": "(0.1V)"},
    # 3132: {"name": "T-INV_Curr", "unit": "(0.01A)"},
    # 3133: {"name": "T-INV_Freq", "unit": "(0.01Hz)"},
    # 3134: {"name": "T-INV_Power", "unit": "(1W)"},
    # 3135: {"name": "R-BackUp Volt", "unit": "(0.1V)"},
    # 3136: {"name": "R-BackUp Curr", "unit": "(0.01A)"},
    # 3137: {"name": "R-BackUp Powe r", "unit": "(1W)"},
    # 3138: {"name": "S-BackUp Volt", "unit": "(0.1V)"},
    # 3139: {"name": "S-BackUp Curr", "unit": "(0.01A)"},
    # 3140: {"name": "S-BackUp Power", "unit": "(1W)"},
    # 3141: {"name": "T-BackUp Volt", "unit": "(0.1V)"},
    # 3142: {"name": "T-BackUp Curr", "unit": "(0.01A)"},
    # 3143: {"name": "T-BackUp Power", "unit": "(1W)"},
    # 3144: {"name": "R-Load Power", "unit": "(1W)"},
    # 3145: {"name": "S-Load Power", "unit": "(1W)"},
    # 3146: {"name": "T-Load Power", "unit": "(1W)"},
    # 3147: {"name": "Day Energy (LOAD)", "unit": "(0.1Kwh)"},
    # 3148: {"name": "Month Energy (LOAD )", "unit": "(Kwh)"},
    # 3149: {"name": "04H 3150 Year Energy (LOAD )", "unit": "(Kwh)"},
    # 3152: {"name": "Total Energy ( LOAD)", "unit": "(0.1Kwh)"},
    # 3153: {"name": "04H 3154 On_GRID_COUNT", "unit": ""},
    # 3154: {"name": "On_GRID_COUNT 4 308 U32 04H 3155 04H 3156 PV Temperature", "unit": "(0.1℃)"},
    # 3156: {"name": "PV Temperature", "unit": "(0.1℃)"},
    # 3157: {"name": "LLC Temperature", "unit": "(0.1℃)"},
    # 3161: {"name": "char 04H 3162 Charge_END_TIME -1", "unit": "(ASCII)"},
    # 3163: {"name": "char 04H 3164 Discharge_START_TIME -1", "unit": "(ASCII)"},
    # 3165: {"name": "char 04H 3166 Discharge_END_TIME -1", "unit": "(ASCII)"},
    # 3167: {"name": "char 04H 3168 Charge_START_TIME -2", "unit": "(ASCII)"},
    # 3169: {"name": "char 04H 3170 Charge_END_TIME -2", "unit": "(ASCII)"},
    # 3171: {"name": "char 04H 3172 Discharge_START_TIME -2", "unit": "(ASCII)"},
    # 3173: {"name": "char 04H 3174 Discharge_END_TIME -2", "unit": "(ASCII)"},
    # 3175: {"name": "char 04H 3176 Timing Charge/Discharge", "unit": ""},
    # 3180: {"name": "PV Start Volt", "unit": "(0.1V)"},
    # 3181: {"name": "DRM Enable", "unit": ""},
    # 3182: {"name": "AntiReflux Enable", "unit": ""},
    # 3183: {"name": "AntiReflux Value", "unit": ""},
    # 3184: {"name": "BackUp Output Enable", "unit": ""},
    # 3185: {"name": "Remote Enable", "unit": ""},
    # 3186: {"name": "Boot Delay", "unit": "(S)"},
    # 3194: {"name": "ARM error Code", "unit": ""},
    # 3195: {"name": "Reactive power setting", "unit": "(%)"},
    # 3200: {"name": "Active power setting", "unit": "(%)"},
    # 3201: {"name": "Min Grid voltage", "unit": "(0.1V)"},
    # 3202: {"name": "Max Grid Vlot", "unit": "(0.1V)"},
    # 3203: {"name": "Min Grid Freq", "unit": "(0.01Hz)"},
    # 3205: {"name": "Bypass Volt -Min", "unit": "(0.1V)"},
    # 3206: {"name": "Bypass Volt -Max", "unit": "(0.1V)"},
    # 3207: {"name": "Bypass Freq -Min", "unit": "(0.01Hz)"},
    # 3209: {"name": "Over Volt derate Enable", "unit": ""},
    # 3210: {"name": "Over Freq derate Enable", "unit": ""},
    # 3211: {"name": "Under Volt derate Enable", "unit": ""},
    # 3212: {"name": "Under Freq derate Enable", "unit": ""},
    # 3214: {"name": "Freq Over derate Start", "unit": "(0.01Hz)"},
    # 3216: {"name": "Under Frep derate Start (Charging)", "unit": "(0.01Hz)"},
    # 3217: {"name": "R-Voltage calibration factor", "unit": ""},
    # 3220: {"name": "R-Current calibration factor", "unit": ""},
    # 3223: {"name": "Battery/Voltage calibration factor", "unit": ""},
    # 3228: {"name": "-3238 Inverter SN Number", "unit": "(U8)"},
    # # 3229–3238 are the Inverter Serial Number bytes (ASCII chars)
    # 3229: {"name": "Inverter SN char[1]", "unit": "(ASCII)"},
    # 3230: {"name": "Inverter SN char[2]", "unit": "(ASCII)"},
    # 3231: {"name": "Inverter SN char[3]", "unit": "(ASCII)"},
    # 3232: {"name": "Inverter SN char[4]", "unit": "(ASCII)"},
    # 3233: {"name": "Inverter SN char[5]", "unit": "(ASCII)"},
    # 3234: {"name": "Inverter SN char[6]", "unit": "(ASCII)"},
    # 3235: {"name": "Inverter SN char[7]", "unit": "(ASCII)"},
    # 3236: {"name": "Inverter SN char[8]", "unit": "(ASCII)"},
    # 3237: {"name": "Inverter SN char[9]", "unit": "(ASCII)"},
    # 3238: {"name": "Inverter SN char[10]", "unit": "(ASCII)"},

    # # Date/time (BCD)
    # 3239: {"name": "Year", "unit": "(BCD)"},
    # 3240: {"name": "Month", "unit": "(BCD)"},
    # 3241: {"name": "Date", "unit": "(BCD)"},
    # 3242: {"name": "Hour", "unit": "(BCD)"},
    # 3243: {"name": "Minute", "unit": "(BCD)"},
    # 3244: {"name": "Second", "unit": "(BCD)"},
    # 3245: {"name": "Week", "unit": "(BCD)"},

    # # Settings
    # 3251: {"name": "Generator mode enabled", "unit": "(0/1)"},
    # 3252: {"name": "Island effect enabled", "unit": "(0/1)"},
    # 3253: {"name": "Battery pack forced wake-up", "unit": "(0/1)"},
    # 3254: {"name": "Manual heating film control", "unit": "(0/1/2)"},
    # 3255: {"name": "CT direction", "unit": "(0=positive,1=negative)"},
    # 3256: {"name": "PV1 Current Calibrate", "unit": "(raw)"},
    # 3257: {"name": "PV2 Current Calibrate", "unit": "(raw)"},
    # 3258: {"name": "Grid Subdivide", "unit": "(0–7)"},
    # 3259: {"name": "AC Couple", "unit": "(0/1)"},

    # 3260: {"name": "Charge from grid MAX SOC", "unit": "(%)"},
    # 3261: {"name": "Maintain Minimum SOC Enable", "unit": "(0/1)"},
    # 3262: {"name": "GFCI Check Enable", "unit": "(0/1)"},
    # 3263: {"name": "VRT Enable", "unit": "(0/1)"},
    # 3264: {"name": "CT or Meter", "unit": "(0=CT,1=Meter)"},
    # 3265: {"name": "Meter Brand", "unit": "(0=Acrel,1=Eastron 3PH,...)"},
    # 3266: {"name": "Modbus RS485 Timeout", "unit": "(seconds)"},
    # 3267: {"name": "Realtime Inverter Power Set", "unit": "(W)"},
    # 3268: {"name": "PW (KSTAR only)", "unit": ""},
    # 3269: {"name": "PW (KSTAR only)", "unit": ""},

    # 3270: {"name": "RS485 Power Control Enable", "unit": "(0/1)"},
    # 3272: {"name": "Realtime Charge Percent", "unit": "(%)"},
    # 3273: {"name": "Realtime Discharge Percent", "unit": "(%)"},
    # 3274: {"name": "Parallel Enable", "unit": "(0/1)"},
    # 3275: {"name": "Parallel Address", "unit": "(1–4)"},
    # 3276: {"name": "AFCI Enable", "unit": "(0/1)"},
    # 3277: {"name": "AFCI Level", "unit": "(1–9)"},
    # 3278: {"name": "Used by KSTAR only", "unit": ""},
    # 3279: {"name": "Silent Mode", "unit": "(0/1)"},

    # # 3292–3301 – Battery statistics
    # 3292: {"name": "Total battery discharge", "unit": "(kWh)"},
    # 3294: {"name": "Daily battery discharge", "unit": "(0.1 kWh)"},
    # 3295: {"name": "Reserved battery stat block (skipped)", "unit": ""},
    # 3297: {"name": "Reserved battery stat block (skipped)", "unit": ""},
    # 3299: {"name": "Total battery charge", "unit": "(kWh)"},
    # 3301: {"name": "Daily battery charge", "unit": "(0.1 kWh)"},

    # # Parallel mode & time functions
    # 3305: {"name": "Parallel Type", "unit": "(0=On&Off Grid,1=OnGrid)"},

    # 3313: {"name": "Self-consumption schedule mask", "unit": "(bitmask)"},
    # 3314: {"name": "Self-Consumption Charge Enable", "unit": "(0/1)"},
    # 3317: {"name": "Self-Consumption Charge Start Time", "unit": "(HHMM hex)"},
    # 3318: {"name": "Self-Consumption Charge End Time", "unit": "(HHMM hex)"},

}
